const page=await figma.getNodeByIdAsync('8:10648');await figma.setCurrentPageAsync(page);
const created=[],mutated=[],track=n=>{created.push(n.id);return n;};
for(const style of ['Regular','Medium','Semibold','Bold'])await figma.loadFontAsync({family:'SF Pro',style});
const variableIds={"background":"VariableID:51:5381","surface":"VariableID:51:5382","control":"VariableID:51:5383","border":"VariableID:51:5384","primary":"VariableID:51:5385","secondary":"VariableID:51:5386","muted":"VariableID:51:5387","inverse":"VariableID:51:5388","s4":"VariableID:51:5389","s8":"VariableID:51:5390","s12":"VariableID:51:5391","s16":"VariableID:51:5392","s24":"VariableID:51:5393","s32":"VariableID:51:5394","s48":"VariableID:51:5395","s64":"VariableID:51:5396","r10":"VariableID:51:5397","r20":"VariableID:51:5398","r100":"VariableID:51:5399"},styleIds={"title":"S:206df98ce02e4cf2fd07fa60f2f1cd5868267db2,","section":"S:d2b6d469929bb3071458f957b45463658eccb963,","body":"S:5417b57494517a212b3f696e3e390fd009a1c9a3,","card":"S:62013fb6da493647081042d4415fe4de0f5bb24b,","label":"S:82f38440744cc80733e05ebc99994ffa51e98b38,","caption":"S:16e5267b515d24466990a788a20171bebfa1c8d9,","metric":"S:494b73e11f53d41fde911aa6f4801348327f92a0,"};
const variables={};for(const[k,id]of Object.entries(variableIds))variables[k]=await figma.variables.getVariableByIdAsync(id);
const colors={background:'0A0A0A',surface:'101010',control:'262626',border:'3B3B3B',primary:'FFFFFF',secondary:'A3A3A3',muted:'747474',inverse:'101010',field:'181818',success:'38A64C',error:'D76A6A'};
const rgb=h=>({r:parseInt(h.slice(0,2),16)/255,g:parseInt(h.slice(2,4),16)/255,b:parseInt(h.slice(4,6),16)/255});
const defs={title:[36,42,'Bold'],section:[24,30,'Bold'],body:[16,24,'Regular'],card:[16,19,'Bold'],label:[14,18,'Medium'],caption:[12,16,'Medium'],metric:[24,29,'Semibold']};
function paint(k){const p={type:'SOLID',color:rgb(colors[k])};return variables[k]?figma.variables.setBoundVariableForPaint(p,'color',variables[k]):p;}
function radius(n,v){n.cornerRadius=v;if(variables['r'+v])for(const k of ['topLeftRadius','topRightRadius','bottomLeftRadius','bottomRightRadius'])n.setBoundVariable(k,variables['r'+v]);}
function pad(n,t,r=t,b=t,l=r){n.paddingTop=t;n.paddingRight=r;n.paddingBottom=b;n.paddingLeft=l;for(const[k,v]of [['paddingTop',t],['paddingRight',r],['paddingBottom',b],['paddingLeft',l]])if(variables['s'+v])n.setBoundVariable(k,variables['s'+v]);}
function auto(parent,name,dir='VERTICAL',gap=8,w){const n=track(figma.createAutoLayout(dir));parent.appendChild(n);n.name=name;n.fills=[];n.itemSpacing=gap;if(variables['s'+gap])n.setBoundVariable('itemSpacing',variables['s'+gap]);if(w){n.resize(w,1);n.primaryAxisSizingMode=dir==='VERTICAL'?'AUTO':'FIXED';n.counterAxisSizingMode=dir==='VERTICAL'?'FIXED':'AUTO';}return n;}
function fixed(n,w,h){n.resize(w,h);if('primaryAxisSizingMode'in n){n.primaryAxisSizingMode='FIXED';n.counterAxisSizingMode='FIXED';}return n;}
function txt(parent,content,style='label',color='primary',width){const n=track(figma.createText());parent.appendChild(n);n.name=content;n.fontName={family:'SF Pro',style:defs[style][2]};n.textStyleId=styleIds[style];n.characters=content;n.fills=[paint(color)];if(width){n.textAutoResize='HEIGHT';n.resize(width,n.height);}return n;}
function rule(parent,w){const n=track(figma.createRectangle());parent.appendChild(n);n.name='Divider';n.resize(w,1);n.fills=[paint('control')];return n;}
function comp(parent,name,w,h,dir='HORIZONTAL'){const n=track(figma.createComponent());parent.appendChild(n);n.name=name;n.layoutMode=dir;n.resize(w,h);n.primaryAxisSizingMode='FIXED';n.counterAxisSizingMode='FIXED';n.fills=[];return n;}
function inst(parent,master){const n=track(master.createInstance());parent.appendChild(n);return n;}
function recolor(n,key){for(const c of n.findAll(x=>'fills'in x||'strokes'in x)){if('fills'in c&&Array.isArray(c.fills)&&c.fills.length)c.fills=c.fills.map(p=>p.type==='SOLID'?paint(key):p);if('strokes'in c&&Array.isArray(c.strokes)&&c.strokes.length)c.strokes=c.strokes.map(p=>p.type==='SOLID'?paint(key):p);mutated.push(c.id);}}
const masters={};for(const[name,id]of Object.entries({pin:'1:11',cart:'1:13',trash:'1:29',close:'1:38',promo:'1:42',loader:'66:15153'}))masters[name]=await figma.getNodeByIdAsync(id);
function icon(parent,name,size=16,color='primary'){const n=inst(parent,masters[name]);n.resize(size,size);n.name=name+' icon';recolor(n,color);return n;}
function button(parent,label,w=160,theme='primary'){const n=auto(parent,label,'HORIZONTAL',8);fixed(n,w,44);n.primaryAxisAlignItems='CENTER';n.counterAxisAlignItems='CENTER';n.fills=[paint(theme)];radius(n,10);txt(n,label,'label',theme==='primary'?'inverse':'primary');return n;}
async function click(n,actions){await n.setReactionsAsync([{trigger:{type:'ON_CLICK'},actions}]);mutated.push(n.id);}
const navigate=id=>({type:'NODE',destinationId:id,navigation:'NAVIGATE',transition:null,resetScrollPosition:true});
const change=id=>({type:'NODE',destinationId:id,navigation:'CHANGE_TO',transition:null});

if(page.children.some(n=>n.name==='Prana / Cart — page'))throw new Error('Cart page already exists; resume from ledger.');
const coll=await figma.variables.getVariableCollectionByIdAsync('VariableCollectionId:51:5380');const mode=coll.modes[0].modeId;
for(const key of ['field','success','error']){const name='color/'+key;let v=(await figma.variables.getLocalVariablesAsync()).find(v=>v.name===name&&v.variableCollectionId===coll.id);if(!v){v=figma.variables.createVariable(name,coll,'COLOR');v.scopes=['FRAME_FILL','SHAPE_FILL','TEXT_FILL','STROKE_COLOR'];v.setValueForMode(mode,{...rgb(colors[key]),a:1});v.setVariableCodeSyntax('WEB','var(--prana-'+key+')');}variables[key]=v;}
const board=auto(page,'Prana / Cart — components & behavior','VERTICAL',32,1504);board.x=3164;board.y=1077;pad(board,32);board.fills=[paint('background')];txt(board,'Cart · components & behavior','section');
const header=comp(board,'Prana / Page header',1440,62);pad(header,0,160);header.primaryAxisAlignItems='SPACE_BETWEEN';header.counterAxisAlignItems='CENTER';header.strokes=[paint('surface')];header.strokeBottomWeight=1;header.strokeTopWeight=0;header.strokeLeftWeight=0;header.strokeRightWeight=0;header.description='Prana desktop header aligned to the current catalogue and product-detail screen.';
const delivery=auto(header,'Delivery location','HORIZONTAL',12);delivery.counterAxisAlignItems='CENTER';const pinBox=auto(delivery,'Location','HORIZONTAL',0);fixed(pinBox,36,36);pinBox.primaryAxisAlignItems='CENTER';pinBox.counterAxisAlignItems='CENTER';pinBox.fills=[paint('control')];radius(pinBox,100);icon(pinBox,'pin',16,'secondary');const address=auto(delivery,'Address','VERTICAL',0);txt(address,'Deliver to','caption','secondary');txt(address,'Jl.Paya Padonan No21a','label');
const headerActions=auto(header,'Account and cart','HORIZONTAL',24);headerActions.counterAxisAlignItems='CENTER';const headerCart=auto(headerActions,'Cart','HORIZONTAL',6);pad(headerCart,9,18);headerCart.counterAxisAlignItems='CENTER';headerCart.fills=[paint('primary')];radius(headerCart,100);icon(headerCart,'cart',16,'inverse');txt(headerCart,'Cart','label','inverse');const avatar=auto(headerActions,'Account','HORIZONTAL',0);fixed(avatar,36,36);avatar.primaryAxisAlignItems='CENTER';avatar.counterAxisAlignItems='CENTER';avatar.fills=[{type:'SOLID',color:rgb('C59E76')}];radius(avatar,100);txt(avatar,'AG','caption','inverse');
const row=comp(board,'Prana / Cart item',720,152);row.itemSpacing=20;pad(row,24,0);row.counterAxisAlignItems='CENTER';row.description='Cart row: source image, title, selected options, weight and unit price. Edit opens the existing product configurator with current selections. At one item the left quantity action becomes Remove; at two or more it becomes Decrease. Line total = unit price × quantity.';
const rowPhoto=track(figma.createRectangle());row.appendChild(rowPhoto);rowPhoto.name='Product image';rowPhoto.resize(104,104);rowPhoto.fills=[{type:'IMAGE',imageHash:'1bef10b197b1ec4540bcdfec6a330b18dc95531b',scaleMode:'FILL'}];radius(rowPhoto,20);
const details=auto(row,'Product information','VERTICAL',10,432);const productTitle=txt(details,'Healthy meal plan 2000 kcal (7 days)','card','primary',432);const options=auto(details,'Selected options','VERTICAL',4,432);txt(options,'Papaya Fresh Juice · +3 more','label','secondary',432);const meta=auto(details,'Unit price and weight','HORIZONTAL',0);txt(meta,'$4 each · 300 g','label','secondary');const edit=auto(details,'Edit item','HORIZONTAL',0);txt(edit,'Edit','label');edit.paddingTop=2;edit.paddingBottom=2;
const purchase=auto(row,'Line total and quantity','VERTICAL',0,144);fixed(purchase,144,104);purchase.primaryAxisAlignItems='SPACE_BETWEEN';purchase.counterAxisAlignItems='MAX';const lineTotal=txt(purchase,'$8.00','metric');
const stepper=auto(purchase,'Quantity','HORIZONTAL',8,144);stepper.primaryAxisAlignItems='SPACE_BETWEEN';stepper.counterAxisAlignItems='CENTER';
const minus=auto(stepper,'Decrease or remove','HORIZONTAL',0);fixed(minus,40,40);minus.primaryAxisAlignItems='CENTER';minus.counterAxisAlignItems='CENTER';minus.fills=[paint('control')];radius(minus,100);const minusLabel=txt(minus,'−','body');const trash=icon(minus,'trash');trash.visible=false;const quantity=txt(stepper,'2','label');const plus=auto(stepper,'Increase quantity','HORIZONTAL',0);fixed(plus,40,40);plus.primaryAxisAlignItems='CENTER';plus.counterAxisAlignItems='CENTER';plus.fills=[paint('primary')];radius(plus,100);txt(plus,'+','body','inverse');
const props={};for(const[label,node]of [['Title',productTitle],['Total',lineTotal],['Quantity',quantity]]){const p=row.addComponentProperty(label,'TEXT',node.characters);node.componentPropertyReferences={characters:p};props[label]=p;}
const promoSection=auto(board,'Promo code states','VERTICAL',16);txt(promoSection,'Promo code · existing automatic validation flow','section');const promoVariants=[];
for(const state of ['Idle','Focused','Validating','Applied','Error']){const c=comp(promoSection,'State='+state,304,state==='Error'?78:48,'VERTICAL');c.itemSpacing=8;const field=auto(c,'Promo code field','HORIZONTAL',12,304);fixed(field,304,48);pad(field,0,16);field.counterAxisAlignItems='CENTER';field.fills=[paint('field')];radius(field,10);icon(field,'promo',16,'secondary');const text=txt(field,['Idle','Focused'].includes(state)?'Promo code':'AW2020','label',['Idle','Focused'].includes(state)?'secondary':'primary');text.layoutGrow=1;if(state==='Focused'){field.strokes=[paint('secondary')];field.strokeWeight=1;}if(state==='Validating')icon(field,'loader',16,'secondary');if(state==='Applied')txt(field,'Applied','caption','success');if(state==='Error'){field.strokes=[paint('error')];field.strokeWeight=1;txt(c,'Promo code not found','caption','error',304);}promoVariants.push(c);}
const promoSet=track(figma.combineAsVariants(promoVariants,promoSection));promoSet.name='Prana / Cart promo code';promoSet.description='Matches the existing checkout flow (65:10268): idle, focus, automatic validation, applied, error. No extra Apply step. AW2020 is the existing reference value, not a new promotion. The validated response supplies the discount; no discount amount is invented.';
for(let i=0;i<promoVariants.length;i++){promoVariants[i].x=(i%3)*328;promoVariants[i].y=Math.floor(i/3)*104;}promoSet.resizeWithoutConstraints(960,182);promoSet.fills=[];await click(promoVariants[0],[change(promoVariants[1].id)]);
const notes=auto(board,'Behavior and data notes','VERTICAL',10,1440);txt(notes,'Implementation notes','section');
for(const line of ['Content width 1120 px. Items 720 px + gap 48 px + summary 352 px.','Summary stays at top 96 px while the item list scrolls. Sticky is an implementation specification.','6 items × $4 = $24.00. Delivery is free as in the source. Original $158.50 was inconsistent.','Titles, photos, weight and selected-option summary are retained from the drawer as source placeholders.','Edit / +3 more opens the existing configurator. Checkout continues to the existing checkout flow.','Promo states follow the existing checkout component; success and error come from validation.','Removing the last item shows the empty cart; Clear cart requests one confirmation.'])txt(notes,line,'label','secondary',1376);
function screen(name,x){const n=auto(page,name,'VERTICAL',0,1440);n.x=x;n.y=-102;fixed(n,1440,919);n.fills=[paint('background')];n.counterAxisAlignItems='CENTER';n.clipsContent=true;n.placeholder=true;inst(n,header);return n;}
const filled=screen('Prana / Cart — page',3164),empty=screen('Prana / Cart — empty',4764);
const content=auto(filled,'Cart content','VERTICAL',24,1120);content.paddingTop=40;const back=auto(content,'Back to menu','HORIZONTAL',0);txt(back,'Back to menu','label','secondary');
const heading=auto(content,'Cart heading','HORIZONTAL',0,720);heading.primaryAxisAlignItems='SPACE_BETWEEN';heading.counterAxisAlignItems='CENTER';const headingLabel=auto(heading,'Cart title and count','HORIZONTAL',12);headingLabel.counterAxisAlignItems='CENTER';txt(headingLabel,'Cart','title');const countText=txt(headingLabel,'6 items','label','secondary');const clear=auto(heading,'Clear cart','HORIZONTAL',8);clear.counterAxisAlignItems='CENTER';icon(clear,'trash',16,'secondary');txt(clear,'Clear cart','label','secondary');
const main=auto(content,'Cart layout / items + summary','HORIZONTAL',48,1120);main.counterAxisAlignItems='MIN';const list=auto(main,'Cart items','VERTICAL',0,720);rule(list,720);
const rows=[];for(const hash of ['1bef10b197b1ec4540bcdfec6a330b18dc95531b','24bcf6a0302588d3adbf1a43b666c92748f9d501','4b193ccedded145bf84e4242ad703c72932f8707']){const n=inst(list,row);const p=n.findOne(n=>n.name==='Product image');p.fills=[{type:'IMAGE',imageHash:hash,scaleMode:'FILL'}];mutated.push(p.id);rows.push(n);rule(list,720);}
const summary=auto(main,'Order summary / sticky top 96','VERTICAL',24,352);pad(summary,24);summary.fills=[paint('surface')];radius(summary,20);txt(summary,'Order summary','section');const promo=inst(summary,promoVariants[0]);rule(summary,304);
const totals=auto(summary,'Order calculation','VERTICAL',16,304);function amount(parent,label,value,color='primary',style='label'){const r=auto(parent,label,'HORIZONTAL',0,304);r.primaryAxisAlignItems='SPACE_BETWEEN';r.counterAxisAlignItems='CENTER';txt(r,label,style,'secondary');return txt(r,value,style,color);}
const subtotal=amount(totals,'Subtotal · 6 items','$24.00');amount(totals,'Delivery','Free');rule(summary,304);const totalRow=auto(summary,'Total','HORIZONTAL',0,304);totalRow.primaryAxisAlignItems='SPACE_BETWEEN';totalRow.counterAxisAlignItems='CENTER';txt(totalRow,'Total','card');const total=txt(totalRow,'$24.00','section');const checkout=button(summary,'Proceed to checkout',304);
const emptyContent=auto(empty,'Empty cart content','VERTICAL',24,1120);emptyContent.paddingTop=40;const emptyBack=auto(emptyContent,'Back to menu','HORIZONTAL',0);txt(emptyBack,'Back to menu','label','secondary');txt(emptyContent,'Cart','title');const emptyState=auto(emptyContent,'Empty cart','VERTICAL',24,1120);emptyState.paddingTop=112;emptyState.counterAxisAlignItems='CENTER';const emptyIcon=auto(emptyState,'Empty cart icon','HORIZONTAL',0);fixed(emptyIcon,64,64);emptyIcon.primaryAxisAlignItems='CENTER';emptyIcon.counterAxisAlignItems='CENTER';emptyIcon.fills=[paint('surface')];radius(emptyIcon,100);icon(emptyIcon,'cart',28,'secondary');txt(emptyState,"It's empty for now",'section');const browse=button(emptyState,'Add food to cart',184);
const confirm=auto(page,'Prana / Cart — clear confirmation','VERTICAL',24,384);confirm.x=4764;confirm.y=1077;pad(confirm,24);confirm.fills=[paint('surface')];radius(confirm,20);txt(confirm,'Clear your cart?','section');txt(confirm,'All items will be removed.','body','secondary',336);const confirmActions=auto(confirm,'Actions','HORIZONTAL',12,336);const cancel=button(confirmActions,'Cancel',162,'control'),confirmClear=button(confirmActions,'Clear cart',162);await click(cancel,[{type:'CLOSE'}]);await click(clear,[{type:'NODE',destinationId:confirm.id,navigation:'OVERLAY',transition:null}]);
filled.placeholder=false;empty.placeholder=false;
return {createdNodeIds:created,mutatedNodeIds:mutated,filled:filled.id,empty:empty.id,board:board.id,header:header.id,row:row.id,rowProperties:props,rows:rows.map(r=>r.id),promoSet:promoSet.id,promoVariants:promoVariants.map(n=>({id:n.id,state:n.name})),promoInstance:promo.id,countText:countText.id,subtotal:subtotal.id,total:total.id,clear:clear.id,confirmation:confirm.id,confirmClear:confirmClear.id,summary:summary.id,checkout:checkout.id,notes:notes.id,colors:Object.fromEntries(['field','success','error'].map(k=>[k,variables[k].id])),bounds:{filled:[filled.x,filled.y,filled.width,filled.height],summary:[summary.width,summary.height],list:[list.width,list.height]},textCount:filled.findAllWithCriteria({types:['TEXT']}).length};

