const page=await figma.getNodeByIdAsync('8:10648');await figma.setCurrentPageAsync(page);
const created=[],mutated=[],track=n=>{created.push(n.id);return n;};
for(const style of ['Regular','Medium','Semibold','Bold'])await figma.loadFontAsync({family:'SF Pro',style});
const variableIds={"background":"VariableID:51:5381","surface":"VariableID:51:5382","control":"VariableID:51:5383","border":"VariableID:51:5384","primary":"VariableID:51:5385","secondary":"VariableID:51:5386","muted":"VariableID:51:5387","inverse":"VariableID:51:5388","s4":"VariableID:51:5389","s8":"VariableID:51:5390","s12":"VariableID:51:5391","s16":"VariableID:51:5392","s24":"VariableID:51:5393","s32":"VariableID:51:5394","s48":"VariableID:51:5395","s64":"VariableID:51:5396","r10":"VariableID:51:5397","r20":"VariableID:51:5398","r100":"VariableID:51:5399"},styleIds={"title":"S:206df98ce02e4cf2fd07fa60f2f1cd5868267db2,","section":"S:d2b6d469929bb3071458f957b45463658eccb963,","body":"S:5417b57494517a212b3f696e3e390fd009a1c9a3,","card":"S:62013fb6da493647081042d4415fe4de0f5bb24b,","label":"S:82f38440744cc80733e05ebc99994ffa51e98b38,","caption":"S:16e5267b515d24466990a788a20171bebfa1c8d9,","metric":"S:494b73e11f53d41fde911aa6f4801348327f92a0,"};
const variables={};for(const[k,id]of Object.entries(variableIds))variables[k]=await figma.variables.getVariableByIdAsync(id);
const colors={background:'0A0A0A',surface:'101010',control:'262626',border:'3B3B3B',primary:'FFFFFF',secondary:'A3A3A3',muted:'747474',inverse:'101010',field:'181818',success:'38A64C',error:'D76A6A'};
const rgb=h=>({r:parseInt(h.slice(0,2),16)/255,g:parseInt(h.slice(2,4),16)/255,b:parseInt(h.slice(4,6),16)/255});
const defs={title:[36,42,'Bold'],section:[24,30,'Bold'],body:[16,24,'Regular'],card:[16,19,'Bold'],label:[14,18,'Medium'],caption:[12,16,'Medium'],metric:[24,29,'Semibold']};
function paint(k){const p={type:'SOLID',color:rgb(colors[k])};return variables[k]?figma.variables.setBoundVariableForPaint(p,'color',variables[k]):p;}
function radius(n,v){n.cornerRadius=v;if(variables['r'+v])for(const k of ['topLeftRadius','topRightRadius','bottomLeftRadius','bottomRightRadius'])n.setBoundVariable(k,variables['r'+v]);}
function pad(n,t,r=t,b=t,l=r){n.paddingTop=t;n.paddingRight=r;n.paddingBottom=b;n.paddingLeft=l;for(const[k,v]of [['paddingTop',t],['paddingRight',r],['paddingBottom',b],['paddingLeft',l]])if(variables['s'+v])n.setBoundVariable(k,variables['s'+v]);}
function auto(parent,name,dir='VERTICAL',gap=8,w){const n=track(figma.createAutoLayout(dir));parent.appendChild(n);n.name=name;n.fills=[];n.itemSpacing=gap;if(variables['s'+gap])n.setBoundVariable('itemSpacing',variables['s'+gap]);if(w){n.resize(w,1);n.primaryAxisSizingMode=dir==='VERTICAL'?'AUTO':'FIXED';n.counterAxisSizingMode=dir==='VERTICAL'?'FIXED':'AUTO';}return n;}
function fixed(n,w,h){n.resize(w,h);if('primaryAxisSizingMode'in n){n.primaryAxisSizingMode='FIXED';n.counterAxisSizingMode='FIXED';}return n;}
function txt(parent,content,style='label',color='primary',width){const n=track(figma.createText());parent.appendChild(n);n.name=content;n.fontName={family:'SF Pro',style:defs[style][2]};n.textStyleId=styleIds[style];n.characters=content;n.fills=[paint(color)];if(width){n.textAutoResize='HEIGHT';n.resize(width,n.height);}return n;}
function rule(parent,w){const n=track(figma.createRectangle());parent.appendChild(n);n.name='Divider';n.resize(w,1);n.fills=[paint('control')];return n;}
function comp(parent,name,w,h,dir='HORIZONTAL'){const n=track(figma.createComponent());parent.appendChild(n);n.name=name;n.layoutMode=dir;n.resize(w,h);n.primaryAxisSizingMode='FIXED';n.counterAxisSizingMode='FIXED';n.fills=[];return n;}
function inst(parent,master){const n=track(master.createInstance());parent.appendChild(n);return n;}
function recolor(n,key){for(const c of n.findAll(x=>'fills'in x||'strokes'in x)){if('fills'in c&&Array.isArray(c.fills)&&c.fills.length)c.fills=c.fills.map(p=>p.type==='SOLID'?paint(key):p);if('strokes'in c&&Array.isArray(c.strokes)&&c.strokes.length)c.strokes=c.strokes.map(p=>p.type==='SOLID'?paint(key):p);mutated.push(c.id);}}
const masters={};for(const[name,id]of Object.entries({pin:'1:11',cart:'1:13',trash:'1:29',close:'1:38',promo:'1:42',loader:'66:15153'}))masters[name]=await figma.getNodeByIdAsync(id);
function icon(parent,name,size=16,color='primary'){const n=inst(parent,masters[name]);n.resize(size,size);n.name=name+' icon';recolor(n,color);return n;}
function button(parent,label,w=160,theme='primary'){const n=auto(parent,label,'HORIZONTAL',8);fixed(n,w,44);n.primaryAxisAlignItems='CENTER';n.counterAxisAlignItems='CENTER';n.fills=[paint(theme)];radius(n,10);txt(n,label,'label',theme==='primary'?'inverse':'primary');return n;}
async function click(n,actions){await n.setReactionsAsync([{trigger:{type:'ON_CLICK'},actions}]);mutated.push(n.id);}
const navigate=id=>({type:'NODE',destinationId:id,navigation:'NAVIGATE',transition:null,resetScrollPosition:true});
const change=id=>({type:'NODE',destinationId:id,navigation:'CHANGE_TO',transition:null});

const rowMaster=await figma.getNodeByIdAsync('74:5927');const trashMaster=rowMaster.findOne(n=>n.name==='trash icon'),minusMaster=rowMaster.findOne(n=>n.type==='TEXT'&&n.characters==='−');const removeProp=rowMaster.addComponentProperty('Show remove','BOOLEAN',false),minusProp=rowMaster.addComponentProperty('Show decrease','BOOLEAN',true);trashMaster.componentPropertyReferences={visible:removeProp};minusMaster.componentPropertyReferences={visible:minusProp};mutated.push(rowMaster.id,trashMaster.id,minusMaster.id);
const collection=figma.variables.createVariableCollection('Prana / Cart prototype');const mode=collection.modes[0].modeId;const vars={};
function variable(name,type,value){const v=figma.variables.createVariable(name,collection,type);v.scopes=type==='BOOLEAN'?['ALL_SCOPES']:['TEXT_CONTENT'];v.setValueForMode(mode,value);vars[name]=v.id;return v;}
const quantityAll=variable('Order/quantity','FLOAT',6),subtotal=variable('Order/subtotal','FLOAT',24),countLabel=variable('Order/count label','STRING','6 items'),subtotalLabel=variable('Order/subtotal label','STRING','Subtotal · 6 items'),money=variable('Order/total label','STRING','$24.00');
const data=(value,type)=>({type,resolvedType:type,value});const alias=v=>({type:'VARIABLE_ALIAS',resolvedType:v.resolvedType,value:figma.variables.createVariableAlias(v)});const expr=(fn,args,type)=>({type:'EXPRESSION',resolvedType:type,value:{expressionFunction:fn,expressionArguments:args}});const set=(v,value)=>({type:'SET_VARIABLE',variableId:v.id,variableValue:value});const str=v=>data(v,'STRING'),num=v=>data(v,'FLOAT');const concat=(a,b)=>expr('ADDITION',[a,b],'STRING');const dollars=v=>concat(concat(str('$'),v),str('.00'));const op=(fn,v,n)=>expr(fn,[alias(v),num(n)],'FLOAT');
const countText=await figma.getNodeByIdAsync('74:6037'),subtotalText=await figma.getNodeByIdAsync('74:6118'),totalText=await figma.getNodeByIdAsync('74:6125');countText.setBoundVariable('characters',countLabel);subtotalText.setBoundVariable('characters',money);totalText.setBoundVariable('characters',money);const subtotalCaption=subtotalText.parent.findOne(n=>n.type==='TEXT'&&n.characters.startsWith('Subtotal'));subtotalCaption.setBoundVariable('characters',subtotalLabel);mutated.push(countText.id,subtotalText.id,totalText.id,subtotalCaption.id);
const refreshOrder=[set(countLabel,concat(alias(quantityAll),str(' items'))),set(subtotalLabel,concat(str('Subtotal · '),concat(alias(quantityAll),str(' items')))),set(money,dollars(alias(subtotal)))];
const allRowVars=[];for(let i=0;i<3;i++){const row=await figma.getNodeByIdAsync(["74:6045","74:6065","74:6085"][i]);const q=variable('Item '+(i+1)+'/quantity','FLOAT',2),label=variable('Item '+(i+1)+'/quantity label','STRING','2'),total=variable('Item '+(i+1)+'/line total','STRING','$8.00'),visible=variable('Item '+(i+1)+'/visible','BOOLEAN',true),showRemove=variable('Item '+(i+1)+'/show remove','BOOLEAN',false),showDecrease=variable('Item '+(i+1)+'/show decrease','BOOLEAN',true);row.setProperties({['Quantity#74:5']:figma.variables.createVariableAlias(label),['Total#74:4']:figma.variables.createVariableAlias(total),[removeProp]:figma.variables.createVariableAlias(showRemove),[minusProp]:figma.variables.createVariableAlias(showDecrease)});row.setBoundVariable('visible',visible);const divider=row.parent.children[row.parent.children.indexOf(row)+1];divider.setBoundVariable('visible',visible);mutated.push(row.id,divider.id);
const refreshItem=[set(label,concat(alias(q),str(''))),set(total,dollars(expr('MULTIPLICATION',[alias(q),num(4)],'FLOAT'))),set(showRemove,expr('EQUALS',[alias(q),num(1)],'BOOLEAN')),set(showDecrease,expr('GREATER_THAN',[alias(q),num(1)],'BOOLEAN')),set(visible,expr('GREATER_THAN',[alias(q),num(0)],'BOOLEAN'))];
const plus=row.findOne(n=>n.name==='Increase quantity'),minus=row.findOne(n=>n.name==='Decrease or remove');
await click(plus,[set(q,op('ADDITION',q,1)),set(quantityAll,op('ADDITION',quantityAll,1)),set(subtotal,op('ADDITION',subtotal,4)),...refreshItem,...refreshOrder]);
await click(minus,[set(q,op('SUBTRACTION',q,1)),set(quantityAll,op('SUBTRACTION',quantityAll,1)),set(subtotal,op('SUBTRACTION',subtotal,4)),...refreshItem,...refreshOrder,{type:'CONDITIONAL',conditionalBlocks:[{condition:expr('EQUALS',[alias(quantityAll),num(0)],'BOOLEAN'),actions:[navigate('74:6015')]}]}]);
allRowVars.push({q,label,total,visible,showRemove,showDecrease});}
const clear=await figma.getNodeByIdAsync('74:6145');const clearActions=[];for(const v of allRowVars)clearActions.push(set(v.q,num(0)),set(v.label,str('0')),set(v.total,str('$0.00')),set(v.visible,data(false,'BOOLEAN')));clearActions.push(set(quantityAll,num(0)),set(subtotal,num(0)),...refreshOrder,navigate('74:6015'));await click(clear,clearActions);
const confirm=await figma.getNodeByIdAsync('74:6139');const clearTrigger=await figma.getNodeByIdAsync('74:6038');await click(clearTrigger,[{type:'NODE',destinationId:confirm.id,navigation:'OVERLAY',transition:null}]);
const notes=await figma.getNodeByIdAsync('74:5990');txt(notes,'Cart prototype: each row has independent quantity; totals recalculate and the last removal opens Empty.','label','secondary',1376);txt(notes,'Menu, item editor and checkout live on other Figma pages; those destinations are specified, not simulated here.','label','secondary',1376);mutated.push(notes.id);
const review=auto(page,'Prana / Cart — promo states','VERTICAL',24,1032);review.x=4764;review.y=1397;pad(review,24);review.fills=[paint('background')];txt(review,'Promo code states','section');const reviewGrid=auto(review,'States','VERTICAL',24);const first=auto(reviewGrid,'Idle · Focus · Validating','HORIZONTAL',24),second=auto(reviewGrid,'Applied · Error','HORIZONTAL',24);
for(let i=0;i<[{"id":"74:5949","state":"State=Idle"},{"id":"74:5956","state":"State=Focused"},{"id":"74:5963","state":"State=Validating"},{"id":"74:5972","state":"State=Applied"},{"id":"74:5980","state":"State=Error"}].length;i++){const def=[{"id":"74:5949","state":"State=Idle"},{"id":"74:5956","state":"State=Focused"},{"id":"74:5963","state":"State=Validating"},{"id":"74:5972","state":"State=Applied"},{"id":"74:5980","state":"State=Error"}][i];const group=auto(i<3?first:second,def.state.replace('State=',''),'VERTICAL',8,304);txt(group,def.state.replace('State=',''),'caption','secondary');inst(group,await figma.getNodeByIdAsync(def.id));}
await review.screenshot({scale:1});await confirm.screenshot({scale:1});
return {createdNodeIds:created,mutatedNodeIds:mutated,prototypeCollection:collection.id,variables:vars,booleanProperties:{remove:removeProp,decrease:minusProp},promoReview:review.id,validation:{independentRows:3,startCount:6,startSubtotal:24,price:4,sourceFrame:'8:10681',filled:'74:5999',empty:'74:6015'}};
